USE [master]
GO

/****** Object:  Database [bist]    Script Date: 9.06.2024 13:39:02 ******/
CREATE DATABASE [bist]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'bist', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\bist.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'bist_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\bist_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [bist] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bist].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [bist] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [bist] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [bist] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [bist] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [bist] SET ARITHABORT OFF 
GO

ALTER DATABASE [bist] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [bist] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [bist] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [bist] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [bist] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [bist] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [bist] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [bist] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [bist] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [bist] SET  DISABLE_BROKER 
GO

ALTER DATABASE [bist] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [bist] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [bist] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [bist] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [bist] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [bist] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [bist] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [bist] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [bist] SET  MULTI_USER 
GO

ALTER DATABASE [bist] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [bist] SET DB_CHAINING OFF 
GO

ALTER DATABASE [bist] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [bist] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [bist] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [bist] SET  READ_WRITE 
GO

